### PR TITLE
build(ci): add github action release and publish

### PR DESCRIPTION
**Pull request by ahnpnl**
## Summary

Automatic release based on tag. How to do it:

- Create a tag in local. If a tag includes **rc/next**, action will publish under **next** tag otherwise action will publish under **latest** tag. For example:

   + v9.0.0-next.2/v9.0.0-rc.0: **next** tag
   + v9.0.0: **latest** tag

- Push the tag to upstream (https://github.com/thymikee/jest-preset-angular)

- Cheers 🥂 

## Test plan

This script is copied from `ts-jest` and it has been already verified working there.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
**N.A.**

### CODE REVIEW

**Comment by ahnpnl** [comment]
@wtho do you agree with those rules ?

**Comment by wtho** [comment]
We will need MFA on mom to be disabled, don't we?

**Comment by ahnpnl** [comment]
No we don't need. I have already switched authentication mode to new mode https://github.blog/changelog/2020-10-02-npm-automation-tokens/ which doesn't require authentication for CI to publish

**Review by wtho — APPROVED** [review]
lgtm

**Pull request merged**
