### PR TITLE
fix: supporting angular 14 alpha

### PR DESCRIPTION
**Pull request by satanTime**
## Summary

fix renovate bot to avoid npm install failures on Angular 14-next, and make pipelines green.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: a14@0.0.0
npm ERR! Found: @angular-devkit/build-angular@14.0.0-next.13
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"14.0.0-next.13" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/build-angular@">=0.1102.19 <14.0.0" from jest-preset-angular@12.0.0-next.2
npm ERR! node_modules/jest-preset-angular
npm ERR!   dev jest-preset-angular@"12.0.0-next.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /tmp/renovate-cache/others/npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/renovate-cache/others/npm/_logs/2022-05-08T22_11_53_258Z-debug-0.log
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by satanTime** [comment]
Hi @ahnpnl, why do you want to support here Angular 15+ too? I thought that the goal is to support unstable releases in `next` only.

**Comment by ahnpnl** [comment]
This will be merged into `next` branch so it has no impact on stable master

**Comment by satanTime** [comment]
thank you! cannot wait for it and to see smooth builds of angular 14 on CI.

**Comment by ahnpnl** [comment]
You can try this now with `next` tag

**Comment by satanTime** [comment]
thanks! it works well now!

**Pull request merged**
