### PR TITLE
fix: add mock for BrowserAnimationsModule

### PR DESCRIPTION
**Pull request by splincode**
Closed: https://github.com/thymikee/jest-preset-angular/issues/170

### CODE REVIEW

**Comment by thymikee** [comment]
Btw, can we add a small smoke test?

**Comment by ahnpnl** [comment]
> Btw, can we add a small smoke test?

Agree 👍

**Comment by thymikee** [comment]
@wtho is this still needed provided with jsdom v13 or v14?

**Comment by wtho** [comment]
It is already included in jsdom [since vs 11.12](https://github.com/jsdom/jsdom/blob/master/Changelog.md), good catch!
(it was added in cssstyle v1.0, which was udpated in jsdom v11.12).

I also checked on version 13 and the properties area already set.

Yeah, we can update jsdom on occasion, but there are no game-changing features/bugfixes in v14 as far as I can judge.

**Comment by thymikee** [comment]
Awesome! I'll close this PR then. Thanks @splincode!

**Pull request closed without merging**
