### PR TITLE
docs(devs-infra): add troubleshooting resolver cases

### PR DESCRIPTION
**Pull request by blackholegalaxy**
## Summary

Add troubleshooting documentation about some cases that could require using a custom resolver to deal with dependencies errors.

Closes: #1625 

## Test plan

Docs only, MD previewer.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ahnpnl** [comment]
Would you please also add for the same files in https://github.com/thymikee/jest-preset-angular/tree/main/website/versioned_docs?

**Comment by blackholegalaxy** [comment]
In all versions or just 12?

**Comment by blackholegalaxy** [comment]
Done in all versions as it could happen I guess.

**Comment by blackholegalaxy** [comment]
Done on mac without line ending changes :)

**Pull request merged**
