### PR TITLE
build: update project to Angular 17

### PR DESCRIPTION
**Pull request by michaelfaith**
## Summary

This change updates root dependencies to use Angular 17.  It also introduces a new example project with a fully standalone v17 app for testing.

Note: updating to the latest prettier / eslint resulted in some minor formatting updates.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
The `esm` and `esm-isolated` tests under the new example 17 project were timing out for me, but I wasn't sure if that was just something wrong with my local environment, since I've not run this project locally before.  It would be good to confirm that these are running successfully.  If not, I may need some guidance on what might be the issue.  Might be related to this issue #2138

### CODE REVIEW

**Comment by michaelfaith** [comment]
@ahnpnl Curious how you'd like to deal with this kind of code.  If we upgrade TS in the root to 5.2, several props don't exist anymore.  Would you prefer to keep the root version of TS lower to support this compatibility layer, or take it out and increase min version support?

image

**Comment by ahnpnl** [comment]
> @ahnpnl Curious how you'd like to deal with this kind of code. If we upgrade TS in the root to 5.2, several props used in this code don't exist anymore. Would you prefer to keep the root version of TS lower to support this compatibility layer, or take it out and increase min version support?
> 
> image

The files in `src/transformers` and `src/ngtsc` are copy version of Angular codes (with a bit modifications, mostly in `replace-resource.ts`), which are downloaded via `https://github.com/thymikee/jest-preset-angular/blob/main/scripts/prebuild.js`.

According to Angular support policy, after **22th Nov 2023**, the minimum supported version is **v15**. That means the files in The files in `src/transformers` and `src/ngtsc` need to be able to run with Angular 15, 16 and 17.

If some codes have been removed in **v17**, but still exists in **v15** and **v16**, we need to:
- First download the changes in **v17**
- Compare with downloaded version of **v15** and **v16**
- Make the changes in such a way to support all.

**Comment by michaelfaith** [comment]
Great. thanks for the background.  I'll look at the new versions of these files

**Comment by johnc-ftl** [comment]
Thank you for your work on this. I haven't grabbed this branch, but I would bet money that the tests are timing out due to the issue described in #2138. I have not been able to upgrade to Typescript 5 due to #2138. And ng 17 requires TS 5, so that issue definitely needs a fix for ng 17 to work.

**Comment by johncrim** [comment]
Thank you for your work on this. I haven't grabbed this branch, but I would bet money that the tests are timing out due to the issue described in #2138. I have not been able to upgrade to Typescript 5 due to #2138. And ng 17 requires TS 5, so that issue definitely needs a fix for ng 17 to work.

**Comment by michaelfaith** [comment]
Yeah, I didn't anticipate the TypeScript compatibility work that's ultimately required to land this Angular upgrade.  Realistically, it'll be at least another couple weeks before I can get back on this and start to work through that refactor.  Since the TypeScript upgrade could be done separately, if anyone else wants to jump in and do that as a separate change, please feel free.

**Comment by ahnpnl** [comment]
Continue in #2198

**Comment by michaelfaith** [comment]
Thanks for wrapping this up.  Apologies for the delay on my end.  We had a long holiday.

**Pull request closed without merging**
