### PR TITLE
docs: add more troubleshooting docs

### LINKED ISSUE #86: snapshot tests have a lot of whitespace
Some trimming might happen here: https://github.com/thymikee/jest-preset-angular/blob/master/AngularSnapshotSerializer.js, not too sure where to start

### LINKED ISSUE #128: @Input() bindings are not reflected within template snapshot
**Versions used:**

```sh
yarn list v1.3.2
├─ @angular/core@5.2.6
├─ jest-preset-angular@5.1.0
└─ jest@22.4.2
```

Not sure if it's related to this jest preset but wanted to report anyway for anyone else looking for solution, if there is any....

**Let's have a component**

```ts
@Component({
  selector: 'pizza-item',
  template: `
     <h3>{{pizzaName}}</h3>    
    <ul><li *ngFor="let toppingName of toppings">{{toppingName}}</li></ul>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PizzaItemComponent {
  @Input name = ''
  @Input toppings: string[] = []
}
```

**with test:**

```ts
describe('PizzaItemComponent', () => {
  let component: PizzaItemComponent;
  let fixture: ComponentFixture<PizzaItemComponent>;

  beforeEach(
    async(() => {
      TestBed.configureTestingModule({
        declarations: [PizzaItemComponent],
      }).compileComponents();
    })
  );

  beforeEach(() => {
    fixture = TestBed.createComponent(PizzaItemComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it(`should snapshot pizza name @Input`, () => {
    expect(fixture).toMatchSnapshot();

    component.name = 'Chilli pizza';

    fixture.detectChanges();
    expect(fixture).toMatchSnapshot();
  });

  it(`should reflect toppings @Input() via *ngFor`, () => {
    component.toppings = ['first'];
    fixture.detectChanges();

    expect(fixture).toMatchSnapshot();

    component.toppings = ['anchovy', 'tomato', 'chili'];
    fixture.detectChanges();

    expect(fixture).toMatchSnapshot();
  });
});
```

none of `@Input` are reflected within the snapshot

**Snapshots:**
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`PizzaItemComponent should reflect toppings @Input() via *ngFor 1`] = `
<pizza-item
  name=""
  toppings={[Function Array]}
>
       <h3>
  </h3>
      <ul>
  </ul>
</pizza-item>
`;

exports[`PizzaItemComponent should reflect toppings @Input() via *ngFor 2`] = `
<pizza-item
  name=""
  toppings={[Function Array]}
>
       <h3>
  </h3>
      <ul>
  </ul>
</pizza-item>
`;

exports[`PizzaItemComponent should snapshot pizza name @Input 1`] = `
<pizza-item
  name=""
  toppings={[Function Array]}
>
       <h3>
  </h3>
      <ul>
  </ul>
</pizza-item>
`;

exports[`PizzaItemComponent should snapshot pizza name @Input 2`] = `
<pizza-item
  name={[Function String]}
  toppings={[Function Array]}
>
       <h3>
  </h3>
      <ul>
  </ul>
</pizza-item>
`;
```

`@Input()` are rendered only if they are set as default values `@Input() name = 'hello'` otherwise bindings are not reflected at all 

Any suggestions ?

### PR DESCRIPTION
**Pull request by Hotell**
Closes #86

### CODE REVIEW

**Comment by AhnpGit** [comment]
@Hotell sorry I reviewed quite late. If you don't mind, would you please including your example into the example app of the repo ? That would be nice as a place where we have some particular testing examples for Angular app.

**Comment by Hotell** [comment]
oh ! no worries :D I almost forgot that I did the PR , will include those ASAP !

**Comment by Hotell** [comment]
@AhnpGit example app updated, pls re-review, thx

**Comment by AhnpGit** [comment]
@Hotell thank you 👍

**Comment by thymikee** [comment]
Thank you guys, you rock!

**Comment by Hotell** [comment]
👌🍻

**Pull request merged**
