### PR TITLE
fix: restrict version of ts-jest to ~21.1.3

### PR DESCRIPTION
**Pull request by FrozenPandaz**
fixes short term https://github.com/thymikee/jest-preset-angular/issues/195

### CODE REVIEW

**Comment by ahnpnl** [comment]
23.1.3* 😁

**Comment by thymikee** [comment]
Can't we use `~23.9.0`?

**Comment by ahnpnl** [comment]
There is sadly no 23.9.. they jumped from 23.1 to 23.10

**Comment by thymikee** [comment]
Oh, that's unexpected :D

**Comment by FrozenPandaz** [comment]
Oops.. Sorry about that, I edited the message right as you published :(

**Comment by FrozenPandaz** [comment]
My guess is that it is some sort of indication they rewrote the whole package... 

See https://github.com/kulshekhar/ts-jest#versioning

**Pull request merged**
