### PR TITLE
Remove ng version

### LINKED ISSUE #26: Remove `ng-version` from snapshots
See: https://github.com/thymikee/jest-preset-angular/issues/23#issuecomment-296428230

### PR DESCRIPTION
**Pull request by thymikee**
**Summary**

Fixes #26.
Also, prepares for a bugfix in how snapshot serializers are invoked in Jest 20. 
As for now snapshots won't show Text nodes.

### CODE REVIEW

**Comment by samgregory88** [comment]
@thymikee It's happening again in v4 looks like

**Comment by thymikee** [comment]
That's weird, because the [snapshot](https://github.com/thymikee/jest-preset-angular/blob/master/example/src/app/calc/__snapshots__/calc.component.spec.ts.snap) doesn't reflect that, and the tests are passing.

**Comment by thymikee** [comment]
Are you using Jest v21? The example is running on v21.0.1 currently.

**Comment by samgregory88** [comment]
Ok i see the difference, i was using `fixture.debugElement.nativeElement` instead of just fixture. Is this expected if you use the nativeElement?

**Pull request merged**
