### PR TITLE
Import jest zone patch

### PR DESCRIPTION
**Pull request by JLHwung**
This PR is addressed to https://github.com/thymikee/jest-zone-patch/pull/9#issuecomment-445772763.

For the sake of complete git history, I merge the commits into this repository.

There is another LICENSE issue: The `jest-zone-patch` is licensed under BSD-3-Clause while this repository under MIT. I keep the original BSD LICENSE on this PR and left it as-is.

### CODE REVIEW

**Comment by thymikee** [comment]
Please change the license to MIT, I used BSD-3 because just because I was more familiar with it at the time :D

**Comment by JLHwung** [comment]
@thymikee Technically speaking we should inform every contributor of `jest-zone-patch` to ask them if they allow to relicense the code under MIT license.

As this PR is not an emergent one, I think we should stick to a relicensing procedure and then we can merge and go forward.

**Comment by thymikee** [comment]
Ok, so we can leave that for now :)

**Comment by JLHwung** [comment]
@thymikee Cool, I will draft an issue on `jest-zone-patch` to asking allowance from our contributors.

**Comment by thymikee** [comment]
Trying to rebase & merge through GitHub results in conflicts. Are you OK with squashing & merging it? I'm certainly not very interested in the commit history of jest-zone-patch, and it's still gonna be available in the original repository, just archived.

**Comment by JLHwung** [comment]
@thymikee rebase and merge might fail on this unusual cases.

Personally I tend to keep the complete history since it helps during `git blame`. But if you insist on squashing & merging, I am good to go.

**Comment by thymikee** [comment]
Thanks!

**Pull request merged**
