### PR TITLE
Overhaul regex for styleUrls

### PR DESCRIPTION
**Pull request by thymikee**
**Summary**
Broader regex for `styleUrls` handling.
Fixes https://github.com/thymikee/jest-preset-angular/issues/9.

**Test plan**
Test cases I used:
```js
@Component({
  selector: 'xc-media-box-h0',
  templateUrl: './media-box-h0.component.html',
  styleUrls: [ '../media-box.component.scss' ],
})

@Component({
  selector: 'xc-media-box-h0',
  templateUrl: './media-box-h0.component.html',
  styleUrls: ['../media-box.component.scss',
  './media-box-h0.component.scss'],
})

@Component({
  selector: 'xc-media-box-h0',
  templateUrl: './media-box-h0.component.html',
  styleUrls: [
    '../media-box.component.scss',
  ],
})

@Component({
  selector: 'xc-media-box-h0',
  templateUrl: './media-box-h0.component.html',
  styleUrls: [
    '../media-box.component.scss',
    './media-box-h0.component.scss'
  ],
})
```

### CODE REVIEW

**Comment by thymikee** [comment]
@intellix I've added tests for the cases you provided and they pass.

**Comment by intellix** [comment]
It all seems to work for me now as well actually :P LGTM!

**Comment by rmlpp** [comment]
I've encountered a situation where this issue still occurs.

Example:
`
styleUrls: [
    './a.component.scss',
    '../b.css',
    '../c.css'
 ]
`
It appears that having more than 2 lines corrupts the regex. If only 2 lines exist than it seems fine.

I'm using Prettier which formats the code putting the styles in each line and after that Jest stops working and throws SyntaxError (_normalizeTemplateMetadata).

**Comment by thymikee** [comment]
Happy to accept PR fixing that! 

Now that babel supports typescript (in beta) we're technically able to make it properly by transforming ast instead of regex, so that's what I hope to do or review ;) soon

**Pull request merged**
