### PR TITLE
feat: support Jest 29 [follow-up]

### PR DESCRIPTION
**Pull request by Michsior14**
## Summary

Follow-up PR of @Tommy228 (#1901) and @tja4472 (https://github.com/Tommy228/jest-preset-angular/pull/1) work introducing support for jest 29 including fixed tests and documentation.

## Test plan

Tested by @Tommy228 and by running tests inside of examples folder.

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## Other information
Same as in #1901

### CODE REVIEW

**Review by ahnpnl — APPROVED** [review]
thanks!

**Comment by Tommy228** [comment]
Thanks @Michsior14 for following that up.

**Comment by Halfist** [comment]
The error `ts-jest[ts-jest-transformer] (WARN) Define ts-jest config under globals is deprecated` still reproduces in v13.1.1. Jest version is 29.6.1, Angular – 12.

**Comment by krzysztofbogusz91** [comment]
Hello, also facing same issue. The only solution was downgrade.
For angular 15 with:
   "@angular-builders/jest": "^15.0.0",
downgrade to: 
   "@types/jest": "28.1.1",
    "jest": "28.0.0",
    "jest-preset-angular": "12.2.6",

**Comment by Halfist** [comment]
@krzysztofbogusz91, thanks, it worked!

**Comment by Halfist** [comment]
But that's not how it's supposed to work, right?

@Michsior14 @Tommy228

**Pull request merged**
