### PR TITLE
feat: support angular v15 #1838

### PR DESCRIPTION
**Pull request by Coly010**
## Summary

Angular 15 is not currently supported and throws invalid peer deps when used in an Angular 15 repo.

## Test plan

Ran `yarn build`, `yarn test` and `yarn test-examples`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

cc @ahnpnl Let me know if I've missed anything!

Fixes: #1838

### CODE REVIEW

**Comment by ahnpnl** [comment]
I think you need to run `yarn dedupe` to fix the problem.

**Comment by Coly010** [comment]
@ahnpnl Pushed update :)

**Comment by luizhp** [comment]
> @ahnpnl Pushed update :)

thanks a lot. so, what's happen now? which steps are needed to release?

**Review by ahnpnl — APPROVED** [review]

**Comment by ahnpnl** [comment]
Thanks!

**Comment by ahnpnl** [comment]
> > @ahnpnl Pushed update :)
> 
> thanks a lot. so, what's happen now? which steps are needed to release?

Still work left is to adapt to Jest 29, see https://github.com/thymikee/jest-preset-angular/issues/1774#issuecomment-1301100124

**Comment by luizhp** [comment]
> > > @ahnpnl Pushed update :)
> > 
> > 
> > thanks a lot. so, what's happen now? which steps are needed to release?
> 
> Still work left is to adapt to Jest 29, see [#1774 (comment)](https://github.com/thymikee/jest-preset-angular/issues/1774#issuecomment-1301100124)

sorry for bothering, but I just want to learn the steps. tks

**Pull request merged**
