### PR TITLE
Fix preprocessor (add transformOptions parameter with reasonable default)

### LINKED ISSUE #45: Issue when running jest with --coverage
When I run jest --coverage with this preset I get the following error after the tests are run and the coverage calculated:
```
        Failed to write coverage reports:
        ERROR: RangeError: Maximum call stack size exceeded
        STACK: RangeError: Maximum call stack size exceeded
    at Object.fs.mkdirSync (fs.js:923:18)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Code\tech-radar\inkundla.web\node_modules\mkdirp\index.js:78:17)
```
I think it could possibly be related to the way that the ts file paths are represented in the coverage report.

### PR DESCRIPTION
**Pull request by markwhitfeld**
This hopefully fixes #45

### CODE REVIEW

**Comment by thymikee** [comment]
I'll get to this in an hour and hopefully publish a fix.

**Comment by markwhitfeld** [comment]
Thanks! You will notice that I had to do a bit more in terms of handling defaults.
I tried to write a test for it, but it turned out to be rabbit hole because it was a larger acceptance test that included ts-jest behavior.

**Comment by thymikee** [comment]
Forgot that this logic for config.mapCoverage is not valid right now, Jest will set up coverage flags for you. So I've simplified your PR, also bumped Jest to latest.

**Comment by markwhitfeld** [comment]
Great! Less code is more ;)

**Pull request merged**
