### PR TITLE
Bump @angular-devkit/build-angular version

### PR DESCRIPTION
**Pull request by jspenc72**
## Summary

When building angular projects with nx this issue arrises when trying to run `nom i`

```
npm ERR! Found: @angular-devkit/build-angular@15.0.1
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~15.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/build-angular@">=0.1102.19 <15.0.0" from jest-preset-angular@12.2.2
npm ERR! node_modules/jest-preset-angular
npm ERR!   dev jest-preset-angular@"~12.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Fix: 

Bump @angular-devkit/build-angular version to fix dependency resolution with jest-preset-angular@12.2.2

## Test plan

```

❯ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ nice-napi@npm:1.0.2: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:3.2.1: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0000: └ Completed in 11s 112ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.6.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zone.js@npm:0.12.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@npm:4.8.4 can't be found in the cache and will be fetched from the remote registry
➤ YN0066: │ typescript@patch:typescript@npm%3A4.8.4#~builtin<compat/typescript>::version=4.8.4&hash=a1c5e5: Cannot apply hunk #7
➤ YN0000: └ Completed in 31s 245ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.15.15 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.15.13 must be built because it never has been before or the last one failed
➤ YN0007: │ nice-napi@npm:1.0.2 must be built because it never has been before or the last one failed
➤ YN0007: │ jest-preset-angular@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 18s 482ms
➤ YN0000: Done with warnings in 1m 2s
❯ yarn build
  • clean up build
  • clean up previously downloaded assets./src/transformers/downlevel_decorators_transform, ./src/ngtsc
  • downloading Angular Downlevel Decorator Transformer from https://github.com/angular/angular/tree/main/packages/compiler-cli/src/transformers/downlevel_decorators_transform ⇒ ./src/transformers
  • downloading dependencies for Angular Downlevel Decorator Transformer from https://github.com/angular/angular/tree/main/packages/compiler-cli/src/ngtsc/reflection,https://github.com/angular/angular/tree/main/packages/compiler-cli/src/ngtsc/ts_compatibility ⇒ ./src/ngtsc
  • clean up Bazel files src/**/BUILD.bazel
  • clean up Angular test files src/ngtsc/reflection/test
❯ yarn test
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
 PASS  src/config/global-setup.spec.ts
 PASS  src/serializers/html-comment.spec.ts
 PASS  src/config/setup-jest.spec.ts
 PASS  src/resolvers/ng-jest-resolver.spec.ts
 PASS  src/serializers/no-ng-attributes.spec.ts
 PASS  src/presets/index.spec.ts
 PASS  src/serializers/ng-snapshot.spec.ts
 PASS  src/config/ng-jest-config.spec.ts
 PASS  src/serializers/index.spec.ts
 PASS  src/compiler/ng-jest-compiler.spec.ts (8.212 s)
 PASS  src/index.spec.ts (5.18 s)
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
 PASS  e2e/__tests__/ng-deep-import.test.ts (30.775 s)
 PASS  e2e/__tests__/path-mapping.test.ts (31.176 s)
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
 PASS  e2e/__tests__/custom-typings.test.ts (34.69 s)
 PASS  e2e/__tests__/process-js-packages.test.ts (35.531 s)
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
 PASS  e2e/__tests__/partial-ivy-lib.test.ts (40.795 s)
 PASS  e2e/__tests__/full-ivy-lib.test.ts (41.283 s)
 PASS  src/ng-jest-transformer.spec.ts (44.423 s)
 PASS  e2e/__tests__/jest-globals.test.ts (44.644 s)
 PASS  e2e/__tests__/snapshot-serializers.test.ts (43.396 s)
 PASS  e2e/__tests__/babel-support.test.ts (51.968 s)
 PASS  e2e/__tests__/async.test.ts (55.024 s)
 PASS  e2e/__tests__/ast-transformers.test.ts (60.174 s)

Test Suites: 23 passed, 23 total
Tests:       66 passed, 66 total
Snapshots:   16 passed, 16 total
Time:        63.443 s
Ran all test suites.
```

```
yarn test-examples
creating jest-preset-angular bundle

==================== example-app-yarn-workspace@13.0.0 in /Users/jessespencer/dev/thymikee/jest-preset-angular/examples/example-app-yarn-workspace ====================

cleaning up

ensuring all dependencies of target project are installed


installing bundled version of jest-preset-angular

starting the CommonJS tests with isolatedModules: false using: yarn test

...

➤ YN0000: 
➤ YN0000: Test Suites: 2 skipped, 23 passed, 23 of 25 total
➤ YN0000: Tests:       2 skipped, 191 passed, 193 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        36.633 s
➤ YN0000: Ran all test suites.

...

➤ YN0000: Test Suites: 1 passed, 1 total
➤ YN0000: Tests:       1 passed, 1 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        5.604 s
➤ YN0000: Ran all test suites.
➤ YN0000: Done in 50s 961ms


...


➤ YN0000: Test Suites: 2 skipped, 23 passed, 23 of 25 total
➤ YN0000: Tests:       2 skipped, 191 passed, 193 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        20.307 s
➤ YN0000: Ran all test suites.

...

➤ YN0000: Test Suites: 1 passed, 1 total
➤ YN0000: Tests:       1 passed, 1 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        2.906 s
➤ YN0000: Ran all test suites.
➤ YN0000: Done in 32s 550ms


...

➤ YN0000: Test Suites: 2 skipped, 23 passed, 23 of 25 total
➤ YN0000: Tests:       2 skipped, 191 passed, 193 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        61.689 s
➤ YN0000: Ran all test suites.
➤ YN0000: ts-jest[versions] (WARN) Version 29.1.2 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=28.0.0 <29.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
➤ YN0000: 
➤ YN0000: ngcc-jest-processor: running ngcc
➤ YN0000: PASS src/user.service.spec.ts (5.816 s)
➤ YN0000:   UserService
➤ YN0000:     ✓ should be created (35 ms)
➤ YN0000: 
➤ YN0000: Test Suites: 1 passed, 1 total
➤ YN0000: Tests:       1 passed, 1 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        6.95 s
➤ YN0000: Ran all test suites.
➤ YN0000: Done in 1m 18s


...


➤ YN0000: Test Suites: 2 skipped, 23 passed, 23 of 25 total
➤ YN0000: Tests:       2 skipped, 191 passed, 193 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        18.788 s
➤ YN0000: Ran all test suites.


...

➤ YN0000: Test Suites: 1 passed, 1 total
➤ YN0000: Tests:       1 passed, 1 total
➤ YN0000: Snapshots:   0 total
➤ YN0000: Time:        2.177 s
➤ YN0000: Ran all test suites.
➤ YN0000: Done in 29s 536ms


...


Test Suites: 2 skipped, 23 passed, 23 of 25 total
Tests:       2 skipped, 191 passed, 193 total
Snapshots:   0 total
Time:        37.792 s
Ran all test suites.

starting the CommonJS tests with isolatedModules: true using: yarn test-isolated


...

Test Suites: 2 skipped, 23 passed, 23 of 25 total
Tests:       2 skipped, 191 passed, 193 total
Snapshots:   0 total
Time:        59.432 s
Ran all test suites.

starting the ESM tests with isolatedModules: true using: yarn test-esm-isolated
...

Test Suites: 2 skipped, 23 passed, 23 of 25 total
Tests:       2 skipped, 191 passed, 193 total
Snapshots:   0 total
Time:        17.447 s
Ran all test suites.

...

Test Suites: 2 skipped, 24 passed, 24 of 26 total
Tests:       2 skipped, 192 passed, 194 total
Snapshots:   0 total
Time:        19.319 s
Ran all test suites in 2 projects.


```

All Example tests have passed.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jspenc72** [comment]
@thymikee Please approve.

**Comment by ahnpnl** [comment]
We will leave this to bot

**Comment by jspenc72** [comment]
@ahnpnl This has no impact on your project and will fix this issue for everyone using `nx` I wouldn't have gone through the trouble to create the pr just so you could ignore it. if you are fine with a bot doing it will you please approve?

**Comment by ahnpnl** [comment]
Bot already did

**Comment by jspenc72** [comment]
Is the bot going to merge and push a release as well? This is my request.

**Comment by ahnpnl** [comment]
Bot can’t release and we can’t release for now. There is still work left on solving issues with Jest 29 which indicates via console warning. 

It is still possible to release without Jest 29 support but that will require branching from tag 12.2.2 and cherry pick from master to merge into new branch created by tag 12.2.2

**Comment by jspenc72** [comment]
@ahnpnl  Are you saying that if I checkout this: 
https://github.com/thymikee/jest-preset-angular/releases/tag/v12.2.2

and bump the version. you will approve this minor release?

**Comment by ahnpnl** [comment]
Yes that is the way to release a minor one, which simply says cherry pick from https://github.com/thymikee/jest-preset-angular/commit/c629535b68327cf7d81c095c2da05202cb7dca32 

However, the branch won’t be merged into main since it is behind. I can do it since I have time later.

**Comment by jspenc72** [comment]
@ahnpnl Thank you I will watch for it.
This might come in handy.

https://github.com/thymikee/jest-preset-angular/compare/v12.2.2...jspenc72:jest-preset-angular:fix/bump-build-angular?expand=1

**Pull request closed without merging**
