### PR TITLE
Tighten up module mappers to prevent hard-to-debug bugs

### PR DESCRIPTION
**Pull request by thymikee**
Fixes https://github.com/thymikee/jest-preset-angular/issues/41
Fixes https://github.com/thymikee/jest-preset-angular/issues/37

In https://github.com/thymikee/jest-preset-angular/pull/6 we introduced very loose `moduleNameMapper` which resulted in couple of weird bugs and until next Jest release it's impossible to override it.

This PR reverts it and adds some reasonable defaults.
 
Also, because of this `"(.*)"`mapping, while debugging #41 on master version of Jest, I encountered an issue where one of the internal Jest modules was calling path matching the regexp, but couldn't find it under `src` dir. This surfaced only because Jest version on master supports checking if modules in `moduleNameMapper` exist and throws otherwise.

### CODE REVIEW

**Comment by thymikee** [comment]
Targeting this to 3.0.0 release

**Comment by cgatian** [comment]
@thymikee Thank you!

**Comment by Tallyb** [comment]
Do they have a due date for new jest release?

**Comment by thymikee** [comment]
No, it's done when it's done. Jest doesn't have any release scheduling/cycle yet.

**Pull request merged**
