### PR TITLE
feat: add support for svg templates

### PR DESCRIPTION
**Pull request by Granipouss**
## Summary

See issue: https://github.com/thymikee/jest-preset-angular/issues/1055

## Test plan

Honnestly, I am not quite sure hom to test that feature using jest.

I can add a svg file in the examples but I am not sure it would count as proper testing.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ahnpnl** [comment]
Would you pls also edit in the example for:
https://github.com/thymikee/jest-preset-angular/blob/main/website/docs/getting-started/options.md
https://github.com/thymikee/jest-preset-angular/blob/main/website/versioned_docs/version-9.x/getting-started/options.md

**Comment by Granipouss** [comment]
I updated the docs and added the tests, but they seem to pass no matter the the file extension given for the template.

**Comment by ahnpnl** [comment]
Actually the snapshot https://github.com/thymikee/jest-preset-angular/pull/1056/files#diff-5b3b28762bd42d50c2bd19e9c16a175b0a4550cb7ed25f910a5265dfc1faa695 would cover your change.

The test https://github.com/thymikee/jest-preset-angular/pull/1056/files#diff-5456458c4864c648974db790899a94437dc6b8e9f36b4f6b5e539e4e996b82c2 would only to demonstrate that we can also transform svg for`templateUrl` :)

**Review by ahnpnl — APPROVED** [review]
thanks!

**Pull request merged**
