### PR TITLE
feat(deps): extend version support range to Angular 17

### PR DESCRIPTION
**Pull request by FrozenPandaz**
## Summary

Angular 17 is being released sometime this week (Week of November 6th, 2023). This PR allows for users to install `jest-preset-angular` without getting `peerDependency` errors which cause some package managers to fail the install process.

## Test plan

We've tested `jest-preset-angular` + Angular 17 as part of the Angular 17 support for [Nx](https://github.com/nrwl/nx/pull/19689) and everything works other than a peer dependency error.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by ahnpnl — APPROVED** [review]
Thanks!

**Comment by FrozenPandaz** [comment]
Awesome, thank you!

Update: Angular 17 is slated for release on November 8th but we have some things to do in Nx so could you please release a version before that? :crossed_fingers:

**Comment by ahnpnl** [comment]
should be out now :)

**Comment by FrozenPandaz** [comment]
Fantastic, thank you so much! :pray:

**Pull request merged**
